### ISSUE TITLE
with nuxt doesn't work?

### ISSUE THREAD

**Issue by sohepalslamat** [asigloo/vue-dynamic-forms-docs#11]
nuxt v3 is't ready until now

**Comment by alvarosaburido** [comment]
Hello, what do you mean about Nuxt 3? Nuxt is currently version 2.15.6 https://github.com/nuxt/nuxt.js

**Comment by xavsio4** [comment]
I don't know if it the same thing but, by the documentation, adding this plugin via npm and then adding it, as mentioned, as a module in nuxt, gives the following error when launching nuxt: Error: Cannot find module '@asigloo/vue-dynamic-forms/nuxt'  .

**Comment by alvarosabu** [comment]
Nuxt.js doesn't have vue3 support yet (probably later this year). So if you want to use this library with Nuxt, you need to install  the vue2 version prior v3, the latest tag is 2.1.0 https://github.com/asigloo/vue-dynamic-forms/tree/v2.1.0
