### ISSUE TITLE
Repo needs better tags

### ISSUE THREAD

**Issue by OmgImAlexis** [asigloo/vue-dynamic-forms-docs#13]
When searching for a library to use instead of https://vueformulate.com I found nothing. It took just over 6 hours of searching to finally find this repo.

I'm not sure what needs to happen to fix this but something causing this project to not be found as easily as it could be.

One thing I did notice is your `package.json` contains no tags and the repo's tags are missing `vue3`.

**Comment by OmgImAlexis** [comment]
@asigloo can you please move this to the main repo.

Also the docs really should have the GitHub link point to the main repo and not here.

**Comment by alvarosabu** [comment]
Hi @OmgImAlexis  thanks for the information, I updated the repo tags of both repositories, I hope is easier to find now
